import { AsyncLocalStorage } from "node:async_hooks";
import { furinSync } from "@teyik0/furin/sync";
import { drizzleSyncAdapter } from "@teyik0/furin/sync/drizzle";
import { Elysia } from "elysia";
import { apiPlugin } from "../src/api";
import type { TofuDatabase } from "../src/api/lib/db";
import { runtime } from "../src/api/lib/runtime";
import { services } from "../src/api/lib/services";
import { anilistOpening } from "../src/api/modules/anilist/opening";
import type { AutomationService } from "../src/api/modules/automation/service";
import type { DesktopController } from "../src/api/modules/desktop/service";
import { updates } from "../src/api/modules/updates";
import type { UpdatesService } from "../src/api/modules/updates/service";
import { sync as liveSync } from "../src/sync";
import type { EnginePort, InstanceConfig } from "../src/types";
import type { TestSyncOptions } from "./database";

interface DesktopServices {
  desktop: () => DesktopController;
  instance?: () => InstanceConfig;
  nativeSdk?: () => typeof import("electrobun/main");
  updates: () => UpdatesService;
}

interface OpeningServices {
  isDesktop: () => boolean;
  openExternal: (url: string) => Promise<boolean>;
}

interface TestContext {
  automation?: () => AutomationService;
  engine?: () => EnginePort;
  opening?: OpeningServices;
  services?: DesktopServices;
  sync?: TestSyncOptions;
  updates?: () => UpdatesService;
}

const contexts = new AsyncLocalStorage<TestContext>();

// Only test transports override the live host. Concurrent requests retain their own real fixtures.
function bindRuntime<Key extends keyof typeof runtime>(
  key: Key,
  read: (context: TestContext) => (typeof runtime)[Key]
) {
  let value = runtime[key];
  Object.defineProperty(runtime, key, {
    configurable: true,
    get() {
      const context = contexts.getStore();
      return context ? read(context) : value;
    },
    set(next: (typeof runtime)[Key]) {
      value = next;
    },
  });
}

const originalInstance = runtime.instance;
let { syncAdapter: liveAdapter } = services;
const automationAdapters = new WeakMap<TofuDatabase, typeof services.syncAdapter>();
Object.defineProperty(services, "syncAdapter", {
  configurable: true,
  get: () => {
    const context = contexts.getStore();
    const database = context?.automation?.().db;
    if (database) {
      let adapter = automationAdapters.get(database);
      if (!adapter) {
        adapter = drizzleSyncAdapter({ db: database, namespace: "tofu" });
        automationAdapters.set(database, adapter);
      }
      return adapter;
    }
    return context?.sync?.adapter ?? liveAdapter;
  },
  set(next: typeof services.syncAdapter) {
    liveAdapter = next;
  },
});
let { engine: liveEngine } = services;
Object.defineProperty(services, "engine", {
  configurable: true,
  get: () => contexts.getStore()?.engine?.() ?? liveEngine,
  set(next: EnginePort) {
    liveEngine = next;
  },
});
bindRuntime("automation", (context) => context.automation?.());
bindRuntime("updates", (context) => context.updates?.() ?? context.services?.updates());
bindRuntime("desktop", (context) => context.services?.desktop());
bindRuntime("sdk", (context) => context.services?.nativeSdk?.());
bindRuntime("instance", (context) => {
  const instance = context.services?.instance?.();
  return instance
    ? { ...instance, desktop: context.engine?.().mode === "desktop" }
    : originalInstance;
});
bindRuntime("db", (context) => context.automation?.().db ?? context.sync?.db);

const desktopGetter = Object.getOwnPropertyDescriptor(
  Object.getPrototypeOf(services),
  "isDesktop"
)?.get;
if (!desktopGetter) {
  throw new Error("The desktop capability is unavailable");
}
Object.defineProperty(services, "isDesktop", {
  get: () => contexts.getStore()?.opening?.isDesktop() ?? desktopGetter.call(services),
});
const { openExternal } = services;
services.openExternal = (url) =>
  contexts.getStore()?.opening?.openExternal(url) ?? openExternal(url);

function scopedApp(context: TestContext) {
  return new Elysia().wrap(
    (next) =>
      (request, ...rest: unknown[]) =>
        contexts.run(context, () => {
          // Match the idempotency keys generated by Furin's client for ordinary test writes.
          if (
            !(
              ["GET", "HEAD", "OPTIONS"].includes(request.method) ||
              request.headers.has("idempotency-key")
            )
          ) {
            request.headers.set("idempotency-key", crypto.randomUUID());
          }
          return next(request, ...rest);
        })
  );
}

export function createTestApi(
  engine: () => EnginePort,
  sync: TestSyncOptions,
  automation?: () => AutomationService,
  desktop?: DesktopServices
) {
  return scopedApp({ automation, engine, services: desktop, sync })
    .use(furinSync(liveSync))
    .use(apiPlugin);
}

export function createTestUpdatesApi(service: () => UpdatesService, sync: TestSyncOptions) {
  return scopedApp({ sync, updates: service }).group("/api", (app) => app.use(updates));
}

export function createTestAniListOpeningApi(opening: OpeningServices) {
  return scopedApp({ opening }).group("/api", (app) => app.use(anilistOpening));
}
