import { cp, lstat, mkdir, readdir, realpath, rename, rm, symlink } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import type { PluginUI } from "@tofu/plugins";
import { inspectPluginPackage } from "@tofu/plugins/server";
import { Type } from "typebox";
import { Check } from "typebox/value";

const idPattern = /^[a-z][a-z0-9-]*$/;
const digestPattern = /^sha256-([A-Za-z0-9+/]+={0,2})$/;
const generatedHeader = "// Generated by Tofu's trusted plugin compiler.";
const officialPluginIds = new Set(["anilist", "jev", "nyaa", "tsundere", "c411"]);
const sharedModules = new Set([
  "@tofu/plugins",
  "@tofu/ui",
  "@teyik0/furin",
  "react",
  "react-dom",
  "elysia",
  "typebox",
  "@elysia/eden",
]);
const registrySchema = Type.Object({
  plugins: Type.Array(
    Type.Object({
      id: Type.String(),
      integrity: Type.String(),
      name: Type.String(),
      path: Type.String(),
      version: Type.String(),
    })
  ),
  version: Type.Literal(1),
});
const dependenciesSchema = Type.Object({
  dependencies: Type.Optional(Type.Record(Type.String(), Type.String())),
  optionalDependencies: Type.Optional(Type.Record(Type.String(), Type.String())),
  peerDependencies: Type.Optional(Type.Record(Type.String(), Type.String())),
});

export interface InstalledPluginPackage {
  id: string;
  integrity: string;
  name: string;
  path: string;
  version: string;
}
export interface InstallPluginOptions {
  hostDirectory: string;
  replace: boolean;
  sourceDirectory: string;
  trust: boolean;
}
export interface UninstallPluginOptions {
  hostDirectory: string;
  id: string;
}

function cacheDirectory(host: string): string {
  return join(host, ".tofu-plugins");
}
async function linkDirectory(source: string, destination: string): Promise<void> {
  await symlink(source, destination, process.platform === "win32" ? "junction" : "dir");
}
function registryPath(host: string): string {
  return join(cacheDirectory(host), "installed.json");
}
async function canonicalPath(path: string): Promise<string> {
  const absolute = resolve(path);
  try {
    return await realpath(absolute);
  } catch (error) {
    if (!(error instanceof Error && "code" in error) || error.code !== "ENOENT") {
      throw error;
    }
    return join(await canonicalPath(dirname(absolute)), basename(absolute));
  }
}
function moduleSpecifier(from: string, target: string): string {
  const path = relative(dirname(from), target).split(sep).join("/");
  return path.startsWith(".") ? path : `./${path}`;
}

export async function listInstalledPlugins(
  hostDirectory: string
): Promise<InstalledPluginPackage[]> {
  const host = await canonicalPath(hostDirectory);
  const file = Bun.file(registryPath(host));
  if (!(await file.exists())) {
    return [];
  }
  const value: unknown = await file.json();
  if (!Check(registrySchema, value)) {
    throw new Error("The installed plugin registry is invalid");
  }
  const ids = new Set<string>();
  for (const entry of value.plugins) {
    if (!(idPattern.test(entry.id) && digestPattern.test(entry.integrity)) || ids.has(entry.id)) {
      throw new Error("The installed plugin registry contains invalid or duplicate pins");
    }
    assertThirdPartyId(entry.id);
    containedPackage(host, entry.path);
    ids.add(entry.id);
  }
  return value.plugins;
}

function assertThirdPartyId(id: string): void {
  if (officialPluginIds.has(id)) {
    throw new Error(`Plugin ${id} is reserved for an official Tofu plugin`);
  }
}

function containedPackage(host: string, path: string): string {
  const cache = join(cacheDirectory(host), "packages");
  const absolute = resolve(host, path);
  const contained = relative(cache, absolute);
  if (
    isAbsolute(path) ||
    contained === "" ||
    contained === ".." ||
    contained.startsWith(`..${sep}`) ||
    isAbsolute(contained)
  ) {
    throw new Error("Installed plugin paths must stay inside the managed package cache");
  }
  return absolute;
}

async function withLock<Result>(host: string, operation: () => Promise<Result>): Promise<Result> {
  await mkdir(cacheDirectory(host), { recursive: true });
  const lock = join(cacheDirectory(host), ".operation-lock");
  try {
    await mkdir(lock);
  } catch (error) {
    throw new Error("Another plugin operation is running; retry after it finishes", {
      cause: error,
    });
  }
  try {
    return await operation();
  } finally {
    await rm(lock, { force: true, recursive: true });
  }
}

async function writeRegistry(host: string, plugins: InstalledPluginPackage[]): Promise<void> {
  const path = registryPath(host);
  const temporary = `${path}.${crypto.randomUUID()}.tmp`;
  await Bun.write(temporary, JSON.stringify({ plugins, version: 1 }, null, 2));
  await rename(temporary, path);
}

export async function installPlugin(options: InstallPluginOptions): Promise<void> {
  if (!options.trust) {
    throw new Error("Local plugins execute trusted code. Installation requires --trust.");
  }
  const host = await canonicalPath(options.hostDirectory);
  const source = await realpath(options.sourceDirectory);
  const inspected = await inspectPluginPackage(source);
  assertThirdPartyId(inspected.id);
  await withLock(host, async () => {
    const installed = await listInstalledPlugins(host);
    if (installed.some((existing) => existing.id === inspected.id) && !options.replace) {
      throw new Error(
        `Plugin ${inspected.id} is installed; upgrading requires --replace and --trust`
      );
    }
    const digest = Buffer.from(inspected.integrity.slice("sha256-".length), "base64").toString(
      "hex"
    );
    const path = join(".tofu-plugins", "packages", `${inspected.id}-${digest}`);
    const target = containedPackage(host, path);
    if (!(await Bun.file(join(target, "package.json")).exists())) {
      await copyPackage(source, target);
    }
    await inspectPluginPackage(target, { integrity: inspected.integrity });
    await prepareDependencies(host, target, `${inspected.id}-${digest}`);
    const entry = {
      id: inspected.id,
      integrity: inspected.integrity,
      name: inspected.name,
      path,
      version: inspected.version,
    };
    const next = [...installed.filter((plugin) => plugin.id !== entry.id), entry].sort(
      (left, right) => left.id.localeCompare(right.id, "en")
    );
    await generateFromRegistry(host, next);
    await writeRegistry(host, next);
  });
}

async function copyPackage(source: string, destination: string): Promise<void> {
  await mkdir(destination, { recursive: true });
  const children = await readdir(source, { withFileTypes: true });
  await Promise.all(
    children.map(async (entry) => {
      if (entry.name === "node_modules" || entry.name === ".git") {
        return;
      }
      const from = join(source, entry.name);
      const to = join(destination, entry.name);
      if (entry.isDirectory()) {
        await copyPackage(from, to);
      } else if (entry.isFile()) {
        await Bun.write(to, Bun.file(from));
      } else {
        throw new Error("Plugin packages may contain only regular files and directories");
      }
    })
  );
}

async function prepareDependencies(host: string, source: string, key: string): Promise<void> {
  const manifest: unknown = await Bun.file(join(source, "package.json")).json();
  if (!Check(dependenciesSchema, manifest)) {
    throw new Error("Plugin dependencies must be package version strings");
  }
  const dependencies = Object.fromEntries(
    Object.entries(manifest.dependencies ?? {})
      .filter(([name]) => !sharedModules.has(name))
      .map(([name, version]) => {
        if (version.startsWith("workspace:") || version.startsWith("catalog:")) {
          throw new Error(`Resolve ${name} to a portable dependency before installation`);
        }
        if (!version.startsWith("file:")) {
          return [name, version];
        }
        const local = resolve(source, version.slice(5));
        const contained = relative(source, local);
        if (contained === ".." || contained.startsWith(`..${sep}`) || isAbsolute(contained)) {
          throw new Error(
            `Local dependency ${name} must be included inside the inspected plugin package`
          );
        }
        return [name, `file:${local}`];
      })
  );
  const dependencyRoot = join(cacheDirectory(host), "dependencies", key);
  await mkdir(dependencyRoot, { recursive: true });
  await Bun.write(
    join(dependencyRoot, "bunfig.toml"),
    '[install]\nlinker = "hoisted"\npeer = false\n'
  );
  if (Object.keys(dependencies).length > 0) {
    await Bun.write(
      join(dependencyRoot, "package.json"),
      JSON.stringify({ dependencies, name: `tofu-managed-${key}`, private: true })
    );
    const child = Bun.spawn([process.execPath, "install", "--ignore-scripts", "--production"], {
      cwd: dependencyRoot,
      stderr: "pipe",
      stdout: "pipe",
    });
    const [stdout, stderr, code] = await Promise.all([
      new Response(child.stdout).text(),
      new Response(child.stderr).text(),
      child.exited,
    ]);
    if (code !== 0) {
      throw new Error(`Plugin dependency installation failed:\n${stdout}${stderr}`);
    }
  }
  const modules = join(dependencyRoot, "node_modules");
  await mkdir(modules, { recursive: true });
  await Promise.all(
    [...sharedModules].map(async (name) => {
      const hostModule = await resolveHostModule(host, name);
      if (!hostModule) {
        return;
      }
      const target = join(modules, name);
      await mkdir(dirname(target), { recursive: true });
      await rm(target, { force: true, recursive: true });
      await linkDirectory(hostModule, target);
    })
  );
  const packageModules = join(source, "node_modules");
  await rm(packageModules, { force: true, recursive: true });
  await linkDirectory(modules, packageModules);
}

async function resolveHostModule(host: string, name: string): Promise<string | null> {
  let directory = host;
  for (;;) {
    const path = join(directory, "node_modules", name);
    try {
      // biome-ignore lint/performance/noAwaitInLoops: Walk dependency ancestors until the first installed host package is found.
      return await realpath(path);
    } catch (error) {
      if (!(error instanceof Error && "code" in error) || error.code !== "ENOENT") {
        throw error;
      }
    }
    const parent = dirname(directory);
    if (parent === directory) {
      return null;
    }
    directory = parent;
  }
}

interface CompiledPlugin {
  clientPath: string;
  entry: InstalledPluginPackage;
  serverPath: string;
  ui: PluginUI;
}

async function inspectContributions(
  host: string,
  entries: InstalledPluginPackage[]
): Promise<CompiledPlugin[]> {
  return await Promise.all(
    entries.map(async (entry) => {
      const directory = containedPackage(host, entry.path);
      const stats = await lstat(directory);
      if (!stats.isDirectory() || stats.isSymbolicLink()) {
        throw new Error("Installed packages must be ordinary managed directories");
      }
      const inspected = await inspectPluginPackage(directory, { integrity: entry.integrity });
      if (inspected.id !== entry.id) {
        throw new Error("Plugin identity does not match its installed pin");
      }
      const module: unknown = await import(inspected.clientPath);
      if (!module || typeof module !== "object" || !("ui" in module)) {
        throw new Error(`Plugin ${entry.id} must export ui from its client entry`);
      }
      const ui = validateUI(module.ui, entry.id);
      return { clientPath: inspected.clientPath, entry, serverPath: inspected.serverPath, ui };
    })
  );
}

function validateUI(value: unknown, pluginId: string): PluginUI {
  if (!value || typeof value !== "object") {
    throw new Error(`Plugin ${pluginId} exports invalid UI contributions`);
  }
  if ("pages" in value && value.pages !== undefined) {
    if (!Array.isArray(value.pages)) {
      throw new Error("Plugin pages must be an array");
    }
    const ids = new Set<string>();
    for (const page of value.pages) {
      if (
        !page ||
        typeof page !== "object" ||
        typeof page.id !== "string" ||
        !idPattern.test(page.id) ||
        ids.has(page.id) ||
        typeof page.title !== "string" ||
        typeof page.path !== "string" ||
        typeof page.pinnable !== "boolean" ||
        typeof page.route !== "function"
      ) {
        throw new Error(`Plugin ${pluginId} exports invalid or duplicate native pages`);
      }
      if (
        page.path.startsWith("/") ||
        page.path.split("/").some((part: string) => part === ".." || part === ".") ||
        page.path.includes("\\") ||
        page.path.includes("?") ||
        page.path.includes("#")
      ) {
        throw new Error(
          "Plugin page paths must be relative without traversal, query, or fragment components"
        );
      }
      ids.add(page.id);
    }
  }
  return value as PluginUI;
}

async function generateFromRegistry(
  host: string,
  entries: InstalledPluginPackage[]
): Promise<void> {
  const plugins = await inspectContributions(host, entries);
  const generated = join(host, "src/plugin-generated");
  const pagesRoot = join(host, "src/pages/(app)/(extensions)");
  await Promise.all(
    plugins.flatMap(({ entry, ui }) =>
      (ui.pages ?? []).map(async (page) => {
        const path = join(pagesRoot, "extensions", entry.id, `${page.id}.tsx`);
        const file = Bun.file(path);
        if ((await file.exists()) && !(await file.text()).startsWith(generatedHeader)) {
          throw new Error("Installed plugin pages cannot overwrite developer-authored routes");
        }
      })
    )
  );
  await mkdir(generated, { recursive: true });
  const serverFile = join(generated, "server.ts");
  const clientFile = join(generated, "client.ts");
  const pins: { id: string; path: string; integrity: string }[] = [];
  const clientImports: string[] = [];

  const contributions: string[] = [];
  const managedPages = new Set<string>();
  await Promise.all(
    plugins.map(async ({ entry, clientPath, ui }, index) => {
      pins.push({
        id: entry.id,
        integrity: entry.integrity,
        path: relative(cacheDirectory(host), containedPackage(host, entry.path))
          .split(sep)
          .join("/"),
      });
      clientImports.push(
        `import { ui as ui${index} } from ${JSON.stringify(moduleSpecifier(clientFile, clientPath))};`
      );

      const pages = ui.pages ?? [];
      const mappedPages = pages.map((page) => ({
        id: page.id,
        path: `/extensions/${entry.id}/${page.id}`,
      }));
      contributions.push(
        `{ id: ${JSON.stringify(entry.id)}, name: ${JSON.stringify(entry.name)}, ui: ui${index}, pages: ${JSON.stringify(mappedPages)} }`
      );
      await Promise.all(
        pages.map(async (page, pageIndex) => {
          const path = join(pagesRoot, "extensions", entry.id, `${page.id}.tsx`);
          managedPages.add(path);
          const layout = join(host, "src/pages/(app)/_route.tsx");
          await writeChanged(
            path,
            `${generatedHeader}\nimport { ui } from ${JSON.stringify(moduleSpecifier(path, clientPath))};\nimport { route as threadLayout } from ${JSON.stringify(moduleSpecifier(path, layout))};\nconst page = ui.pages?.[${pageIndex}];\nif (!page) { throw new Error("The installed plugin page is unavailable"); }\nexport const route = page.route({ threadLayout });\n`
          );
        })
      );
    })
  );
  await removeStalePages(pagesRoot, managedPages);
  await writeChanged(
    serverFile,
    `// Generated by Tofu's trusted plugin compiler.\nimport type { ErasedPluginDefinition } from "@tofu/plugins";\nimport type { PluginCore } from "@tofu/plugins/server";\nimport { resolve } from "node:path";\nimport { fileURLToPath } from "node:url";\nimport { loadExternalPlugins } from "./runtime";\nexport function externalPlugins(core: PluginCore): Promise<ErasedPluginDefinition[]> {\n  return loadExternalPlugins(core, ${JSON.stringify(pins)}, [\n    fileURLToPath(new URL("../../.tofu-plugins/", import.meta.url)),\n    fileURLToPath(new URL("./plugins/", import.meta.url)),\n    fileURLToPath(new URL("../../../.tofu-plugins/", import.meta.url)),\n    resolve(process.cwd(), ".tofu-plugins"),\n  ]);\n}\n`
  );
  await writeChanged(
    clientFile,
    `// Generated by Tofu's trusted plugin compiler.\nimport type { ExternalPluginUI } from "./empty.client";\n${clientImports.join("\n")}\nexport const externalPluginUIs: ExternalPluginUI[] = [${contributions.join(", ")}];\n`
  );
}

export async function generatePlugins(hostDirectory: string): Promise<void> {
  const host = await canonicalPath(hostDirectory);
  const until = Date.now() + 5000;
  for (let attempt = 0; attempt <= 200; attempt += 1) {
    try {
      // biome-ignore lint/performance/noAwaitInLoops: Concurrent dev and release startups must wait for their shared compiler lock.
      await withLock(host, async () =>
        generateFromRegistry(host, await listInstalledPlugins(host))
      );
      return;
    } catch (error) {
      const cause = error instanceof Error ? error.cause : null;
      if (
        !(cause instanceof Error && "code" in cause && cause.code === "EEXIST") ||
        Date.now() >= until
      ) {
        throw error;
      }
      await Bun.sleep(25);
    }
  }
  throw new Error("Timed out while waiting for the plugin compiler lock");
}

export async function uninstallPlugin(options: UninstallPluginOptions): Promise<void> {
  if (!idPattern.test(options.id)) {
    throw new Error("Plugin IDs must use lowercase letters, digits, and hyphens");
  }
  const host = await canonicalPath(options.hostDirectory);
  await withLock(host, async () => {
    const entries = await listInstalledPlugins(host);
    if (!entries.some((entry) => entry.id === options.id)) {
      throw new Error(`Plugin ${options.id} is not installed`);
    }
    const next = entries.filter((entry) => entry.id !== options.id);
    await generateFromRegistry(host, next);
    await writeRegistry(host, next);
  });
}

/** Materializes reviewed package sources and dependencies beside the packaged Bun server. */
export async function materializePluginRuntime(
  hostDirectory: string,
  destinationDirectory: string
): Promise<void> {
  const host = await canonicalPath(hostDirectory);
  const destination = resolve(destinationDirectory);
  const entries = await listInstalledPlugins(host);
  await Promise.all(
    entries.map((entry) =>
      inspectPluginPackage(containedPackage(host, entry.path), { integrity: entry.integrity })
    )
  );
  const shared =
    entries.length > 0 ? await collectHostDependencies(host) : new Map<string, string>();
  const staged = `${destination}.${crypto.randomUUID()}.tmp`;
  await mkdir(staged, { recursive: true });
  try {
    await Promise.all(
      entries.map(async (entry) => {
        const source = containedPackage(host, entry.path);
        const target = join(staged, relative(cacheDirectory(host), source));
        await copyPackage(source, target);
        try {
          await cp(join(source, "node_modules"), join(target, "node_modules"), {
            dereference: true,
            recursive: true,
          });
        } catch (error) {
          if (!(error instanceof Error && "code" in error) || error.code !== "ENOENT") {
            throw error;
          }
        }
        await inspectPluginPackage(target, { integrity: entry.integrity });
      })
    );
    await Promise.all(
      [...shared].map(async ([name, source]) => {
        await cp(source, join(staged, "node_modules", name), {
          dereference: true,
          recursive: true,
        });
      })
    );
    await Bun.write(
      join(staged, "installed.json"),
      JSON.stringify({ plugins: entries, version: 1 }, null, 2)
    );
    await rm(destination, { force: true, recursive: true });
    await mkdir(dirname(destination), { recursive: true });
    await rename(staged, destination);
  } finally {
    await rm(staged, { force: true, recursive: true });
  }
}

async function collectHostDependencies(host: string): Promise<Map<string, string>> {
  const packages = new Map<string, string>();
  const visited = new Set<string>();
  const visit = async (name: string, parent: string): Promise<void> => {
    const source = await resolveHostModule(parent, name);
    if (!source) {
      return;
    }
    const rootSource = await resolveHostModule(host, name);
    if (!packages.has(name)) {
      packages.set(name, rootSource ?? source);
    }
    if (visited.has(source)) {
      return;
    }
    visited.add(source);
    const manifest: unknown = await Bun.file(join(source, "package.json")).json();
    if (!Check(dependenciesSchema, manifest)) {
      throw new Error(`Shared package ${name} has invalid dependency metadata`);
    }
    const dependencies = new Set([
      ...Object.keys(manifest.dependencies ?? {}),
      ...Object.keys(manifest.optionalDependencies ?? {}),
      ...Object.keys(manifest.peerDependencies ?? {}),
    ]);
    await Promise.all([...dependencies].map((dependency) => visit(dependency, source)));
    if (rootSource && rootSource !== source) {
      await visit(name, host);
    }
  };
  await Promise.all([...sharedModules].map((name) => visit(name, host)));
  return packages;
}

async function writeChanged(path: string, contents: string): Promise<void> {
  const file = Bun.file(path);
  if ((await file.exists()) && (await file.text()) === contents) {
    return;
  }
  await Bun.write(path, contents);
}

async function removeStalePages(root: string, managed: Set<string>): Promise<void> {
  try {
    await lstat(root);
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return;
    }
    throw error;
  }
  const paths = [...new Bun.Glob("**/*.tsx").scanSync(root)];
  await Promise.all(
    paths.map(async (path) => {
      const absolute = join(root, path);
      if (!managed.has(absolute) && (await Bun.file(absolute).text()).startsWith(generatedHeader)) {
        await rm(absolute);
      }
    })
  );
}
