import { join } from "node:path";
import { generate } from "@graphql-codegen/cli";
import config from "../codegen";

const generated: { content: string; filename: string }[] = await generate(config, false);
await Promise.all(
  generated.map(async (file) => {
    const formatting = Bun.spawn(
      [
        process.execPath,
        join(import.meta.dir, "../node_modules/@biomejs/biome/bin/biome"),
        "format",
        "--vcs-enabled=false",
        "--config-path",
        join(import.meta.dir, ".."),
        "--stdin-file-path",
        file.filename,
      ],
      {
        stderr: "inherit",
        stdin: new Blob([
          "// Generated by bun run codegen. Do not edit manually.\n",
          "// biome-ignore-all lint: GraphQL Code Generator owns these declarations.\n",
          "// biome-ignore-all assist: Preserve generated declaration order.\n",
          file.content,
        ]),
        stdout: "pipe",
      }
    );
    const content = await new Response(formatting.stdout).text();
    if (await formatting.exited) {
      throw new Error("Unable to format the generated AniList SDK");
    }
    const previous = (await Bun.file(file.filename).exists())
      ? await Bun.file(file.filename).text()
      : null;
    if (process.argv.includes("--check")) {
      if (previous !== content) {
        throw new Error("The AniList SDK is stale. Run bun run codegen.");
      }
    } else if (previous !== content) {
      await Bun.write(file.filename, content);
    }
  })
);
