// Generated by bun run codegen. Do not edit manually.
// biome-ignore-all lint: GraphQL Code Generator owns these declarations.
// biome-ignore-all assist: Preserve generated declaration order.
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never };
import type { DocumentNode } from "graphql";
export type ExternalLinkType = "INFO" | "SOCIAL" | "STREAMING";

/** The format the media was released in */
export type MediaFormat =
  /** Professionally published manga with more than one chapter */
  | "MANGA"
  /** Anime movies with a theatrical release */
  | "MOVIE"
  /** Short anime released as a music video */
  | "MUSIC"
  /** Written books released as a series of light novels */
  | "NOVEL"
  /** (Original Net Animation) Anime that have been originally released online or are only available through streaming services. */
  | "ONA"
  /** Manga with just one chapter */
  | "ONE_SHOT"
  /** (Original Video Animation) Anime that have been released directly on DVD/Blu-ray without originally going through a theatrical release or television broadcast */
  | "OVA"
  /** Special episodes that have been included in DVD/Blu-ray releases, picture dramas, pilots, etc */
  | "SPECIAL"
  /** Anime broadcast on television */
  | "TV"
  /** Anime which are under 15 minutes in length and broadcast on television */
  | "TV_SHORT";

/** Media list watching/reading status enum. */
export type MediaListStatus =
  /** Finished watching/reading */
  | "COMPLETED"
  /** Currently watching/reading */
  | "CURRENT"
  /** Stopped watching/reading before completing */
  | "DROPPED"
  /** Paused watching/reading */
  | "PAUSED"
  /** Planning to watch/read */
  | "PLANNING"
  /** Re-watching/reading */
  | "REPEATING";

export type MediaSeason =
  /** Predominantly started airing between October and November */
  | "FALL"
  /** Predominantly started airing between April and June */
  | "SPRING"
  /** Predominantly started airing between July and September */
  | "SUMMER"
  /** Predominantly started airing between January and March */
  | "WINTER";

/** Media sort enums */
export type MediaSort =
  | "CHAPTERS"
  | "CHAPTERS_DESC"
  | "DURATION"
  | "DURATION_DESC"
  | "END_DATE"
  | "END_DATE_DESC"
  | "EPISODES"
  | "EPISODES_DESC"
  | "FAVOURITES"
  | "FAVOURITES_DESC"
  | "FORMAT"
  | "FORMAT_DESC"
  | "ID"
  | "ID_DESC"
  | "POPULARITY"
  | "POPULARITY_DESC"
  | "SCORE"
  | "SCORE_DESC"
  | "SEARCH_MATCH"
  | "START_DATE"
  | "START_DATE_DESC"
  | "STATUS"
  | "STATUS_DESC"
  | "TITLE_ENGLISH"
  | "TITLE_ENGLISH_DESC"
  | "TITLE_NATIVE"
  | "TITLE_NATIVE_DESC"
  | "TITLE_ROMAJI"
  | "TITLE_ROMAJI_DESC"
  | "TRENDING"
  | "TRENDING_DESC"
  | "TYPE"
  | "TYPE_DESC"
  | "UPDATED_AT"
  | "UPDATED_AT_DESC"
  | "VOLUMES"
  | "VOLUMES_DESC";

/** Source type the media was adapted from */
export type MediaSource =
  /** Version 2+ only. Japanese Anime */
  | "ANIME"
  /** Version 3 only. Comics excluding manga */
  | "COMIC"
  /** Version 2+ only. Self-published works */
  | "DOUJINSHI"
  /** Version 3 only. Games excluding video games */
  | "GAME"
  /** Written work published in volumes */
  | "LIGHT_NOVEL"
  /** Version 3 only. Live action media such as movies or TV show */
  | "LIVE_ACTION"
  /** Asian comic book */
  | "MANGA"
  /** Version 3 only. Multimedia project */
  | "MULTIMEDIA_PROJECT"
  /** Version 2+ only. Written works not published in volumes */
  | "NOVEL"
  /** An original production not based of another work */
  | "ORIGINAL"
  /** Other */
  | "OTHER"
  /** Version 3 only. Picture book */
  | "PICTURE_BOOK"
  /** Video game */
  | "VIDEO_GAME"
  /** Video game driven primary by text and narrative */
  | "VISUAL_NOVEL"
  /** Version 3 only. Written works published online */
  | "WEB_NOVEL";

/** The current releasing status of the media */
export type MediaStatus =
  /** Ended before the work could be finished */
  | "CANCELLED"
  /** Has completed and is no longer being released */
  | "FINISHED"
  /** Version 2 only. Is currently paused from releasing and will resume at a later date */
  | "HIATUS"
  /** To be released at a later date */
  | "NOT_YET_RELEASED"
  /** Currently releasing */
  | "RELEASING";

export type AniListMediaFragment = {
  id: number;
  synonyms: Array<string | null> | null;
  siteUrl: string | null;
  bannerImage: string | null;
  episodes: number | null;
  format: MediaFormat | null;
  genres: Array<string | null> | null;
  season: MediaSeason | null;
  seasonYear: number | null;
  status: MediaStatus | null;
  averageScore: number | null;
  trending: number | null;
  popularity: number | null;
  favourites: number | null;
  duration: number | null;
  countryOfOrigin: string | null;
  source: MediaSource | null;
  isLicensed: boolean | null;
  isAdult: boolean | null;
  title: {
    romaji: string | null;
    english: string | null;
    native: string | null;
    userPreferred: string | null;
  } | null;
  coverImage: { extraLarge: string | null; large: string | null } | null;
  tags: Array<{ name: string; rank: number | null; isAdult: boolean | null } | null> | null;
  externalLinks: Array<{
    siteId: number | null;
    type: ExternalLinkType | null;
    isDisabled: boolean | null;
  } | null> | null;
  startDate: { year: number | null; month: number | null; day: number | null } | null;
  endDate: { year: number | null; month: number | null; day: number | null } | null;
  nextAiringEpisode: { episode: number; airingAt: number } | null;
  studios: { nodes: Array<{ name: string } | null> | null } | null;
};

export type ViewerQueryVariables = Exact<{ [key: string]: never }>;

export type ViewerQuery = { Viewer: { id: number; name: string } | null };

export type UserQueryVariables = Exact<{
  name: string;
}>;

export type UserQuery = { User: { id: number; name: string } | null };

export type LibraryQueryVariables = Exact<{
  userId: number;
  chunk: number;
}>;

export type LibraryQuery = {
  MediaListCollection: {
    hasNextChunk: boolean | null;
    lists: Array<{
      entries: Array<{
        status: MediaListStatus | null;
        progress: number | null;
        media: {
          id: number;
          synonyms: Array<string | null> | null;
          siteUrl: string | null;
          bannerImage: string | null;
          episodes: number | null;
          format: MediaFormat | null;
          genres: Array<string | null> | null;
          season: MediaSeason | null;
          seasonYear: number | null;
          status: MediaStatus | null;
          averageScore: number | null;
          trending: number | null;
          popularity: number | null;
          favourites: number | null;
          duration: number | null;
          countryOfOrigin: string | null;
          source: MediaSource | null;
          isLicensed: boolean | null;
          isAdult: boolean | null;
          title: {
            romaji: string | null;
            english: string | null;
            native: string | null;
            userPreferred: string | null;
          } | null;
          coverImage: { extraLarge: string | null; large: string | null } | null;
          tags: Array<{ name: string; rank: number | null; isAdult: boolean | null } | null> | null;
          externalLinks: Array<{
            siteId: number | null;
            type: ExternalLinkType | null;
            isDisabled: boolean | null;
          } | null> | null;
          startDate: { year: number | null; month: number | null; day: number | null } | null;
          endDate: { year: number | null; month: number | null; day: number | null } | null;
          nextAiringEpisode: { episode: number; airingAt: number } | null;
          studios: { nodes: Array<{ name: string } | null> | null } | null;
        } | null;
      } | null> | null;
    } | null> | null;
  } | null;
};

export type CatalogQueryVariables = Exact<{
  page: number;
  sort?: Array<MediaSort | null | undefined> | MediaSort | null | undefined;
  search?: string | null | undefined;
  genre_in?: Array<string | null | undefined> | string | null | undefined;
  genre_not_in?: Array<string | null | undefined> | string | null | undefined;
  tag_in?: Array<string | null | undefined> | string | null | undefined;
  tag_not_in?: Array<string | null | undefined> | string | null | undefined;
  seasonYear?: number | null | undefined;
  season?: MediaSeason | null | undefined;
  format?: MediaFormat | null | undefined;
  status?: MediaStatus | null | undefined;
  licensedById?: number | null | undefined;
  countryOfOrigin?: string | null | undefined;
  source?: MediaSource | null | undefined;
  startDate_greater?: number | null | undefined;
  startDate_lesser?: number | null | undefined;
  episodes_greater?: number | null | undefined;
  episodes_lesser?: number | null | undefined;
  duration_greater?: number | null | undefined;
  duration_lesser?: number | null | undefined;
  isLicensed?: boolean | null | undefined;
}>;

export type CatalogQuery = {
  Page: {
    pageInfo: { currentPage: number | null; hasNextPage: boolean | null } | null;
    media: Array<{
      id: number;
      synonyms: Array<string | null> | null;
      siteUrl: string | null;
      bannerImage: string | null;
      episodes: number | null;
      format: MediaFormat | null;
      genres: Array<string | null> | null;
      season: MediaSeason | null;
      seasonYear: number | null;
      status: MediaStatus | null;
      averageScore: number | null;
      trending: number | null;
      popularity: number | null;
      favourites: number | null;
      duration: number | null;
      countryOfOrigin: string | null;
      source: MediaSource | null;
      isLicensed: boolean | null;
      isAdult: boolean | null;
      title: {
        romaji: string | null;
        english: string | null;
        native: string | null;
        userPreferred: string | null;
      } | null;
      coverImage: { extraLarge: string | null; large: string | null } | null;
      tags: Array<{ name: string; rank: number | null; isAdult: boolean | null } | null> | null;
      externalLinks: Array<{
        siteId: number | null;
        type: ExternalLinkType | null;
        isDisabled: boolean | null;
      } | null> | null;
      startDate: { year: number | null; month: number | null; day: number | null } | null;
      endDate: { year: number | null; month: number | null; day: number | null } | null;
      nextAiringEpisode: { episode: number; airingAt: number } | null;
      studios: { nodes: Array<{ name: string } | null> | null } | null;
    } | null> | null;
  } | null;
};

export type CatalogOptionsQueryVariables = Exact<{ [key: string]: never }>;

export type CatalogOptionsQuery = {
  GenreCollection: Array<string | null> | null;
  MediaTagCollection: Array<{
    name: string;
    category: string | null;
    isAdult: boolean | null;
  } | null> | null;
  ExternalLinkSourceCollection: Array<{
    id: number;
    site: string;
    type: ExternalLinkType | null;
    isDisabled: boolean | null;
  } | null> | null;
};

export type SaveProgressMutationVariables = Exact<{
  mediaId: number;
  progress: number;
}>;

export type SaveProgressMutation = { SaveMediaListEntry: { progress: number | null } | null };

export const AniListMediaFragmentDoc = {
  kind: "Document",
  definitions: [
    {
      kind: "FragmentDefinition",
      name: { kind: "Name", value: "AniListMedia" },
      typeCondition: { kind: "NamedType", name: { kind: "Name", value: "Media" } },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          { kind: "Field", name: { kind: "Name", value: "id" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "title" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "romaji" } },
                { kind: "Field", name: { kind: "Name", value: "english" } },
                { kind: "Field", name: { kind: "Name", value: "native" } },
                { kind: "Field", name: { kind: "Name", value: "userPreferred" } },
              ],
            },
          },
          { kind: "Field", name: { kind: "Name", value: "synonyms" } },
          { kind: "Field", name: { kind: "Name", value: "siteUrl" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "coverImage" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "extraLarge" } },
                { kind: "Field", name: { kind: "Name", value: "large" } },
              ],
            },
          },
          { kind: "Field", name: { kind: "Name", value: "bannerImage" } },
          { kind: "Field", name: { kind: "Name", value: "episodes" } },
          { kind: "Field", name: { kind: "Name", value: "format" } },
          { kind: "Field", name: { kind: "Name", value: "genres" } },
          { kind: "Field", name: { kind: "Name", value: "season" } },
          { kind: "Field", name: { kind: "Name", value: "seasonYear" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "status" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "version" },
                value: { kind: "IntValue", value: "2" },
              },
            ],
          },
          { kind: "Field", name: { kind: "Name", value: "averageScore" } },
          { kind: "Field", name: { kind: "Name", value: "trending" } },
          { kind: "Field", name: { kind: "Name", value: "popularity" } },
          { kind: "Field", name: { kind: "Name", value: "favourites" } },
          { kind: "Field", name: { kind: "Name", value: "duration" } },
          { kind: "Field", name: { kind: "Name", value: "countryOfOrigin" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "source" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "version" },
                value: { kind: "IntValue", value: "3" },
              },
            ],
          },
          { kind: "Field", name: { kind: "Name", value: "isLicensed" } },
          { kind: "Field", name: { kind: "Name", value: "isAdult" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "tags" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "name" } },
                { kind: "Field", name: { kind: "Name", value: "rank" } },
                { kind: "Field", name: { kind: "Name", value: "isAdult" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "externalLinks" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "siteId" } },
                { kind: "Field", name: { kind: "Name", value: "type" } },
                { kind: "Field", name: { kind: "Name", value: "isDisabled" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "startDate" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "year" } },
                { kind: "Field", name: { kind: "Name", value: "month" } },
                { kind: "Field", name: { kind: "Name", value: "day" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "endDate" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "year" } },
                { kind: "Field", name: { kind: "Name", value: "month" } },
                { kind: "Field", name: { kind: "Name", value: "day" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "nextAiringEpisode" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "episode" } },
                { kind: "Field", name: { kind: "Name", value: "airingAt" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "studios" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "isMain" },
                value: { kind: "BooleanValue", value: true },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "nodes" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [{ kind: "Field", name: { kind: "Name", value: "name" } }],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode;
export const ViewerDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "Viewer" },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "Viewer" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "id" } },
                { kind: "Field", name: { kind: "Name", value: "name" } },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode;
export const UserDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "User" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "name" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "User" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "name" },
                value: { kind: "Variable", name: { kind: "Name", value: "name" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "id" } },
                { kind: "Field", name: { kind: "Name", value: "name" } },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode;
export const LibraryDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "Library" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "userId" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "chunk" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
          },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "MediaListCollection" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "userId" },
                value: { kind: "Variable", name: { kind: "Name", value: "userId" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "type" },
                value: { kind: "EnumValue", value: "ANIME" },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "chunk" },
                value: { kind: "Variable", name: { kind: "Name", value: "chunk" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "perChunk" },
                value: { kind: "IntValue", value: "500" },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "hasNextChunk" } },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "lists" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      {
                        kind: "Field",
                        name: { kind: "Name", value: "entries" },
                        selectionSet: {
                          kind: "SelectionSet",
                          selections: [
                            { kind: "Field", name: { kind: "Name", value: "status" } },
                            { kind: "Field", name: { kind: "Name", value: "progress" } },
                            {
                              kind: "Field",
                              name: { kind: "Name", value: "media" },
                              selectionSet: {
                                kind: "SelectionSet",
                                selections: [
                                  {
                                    kind: "FragmentSpread",
                                    name: { kind: "Name", value: "AniListMedia" },
                                  },
                                ],
                              },
                            },
                          ],
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
    {
      kind: "FragmentDefinition",
      name: { kind: "Name", value: "AniListMedia" },
      typeCondition: { kind: "NamedType", name: { kind: "Name", value: "Media" } },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          { kind: "Field", name: { kind: "Name", value: "id" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "title" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "romaji" } },
                { kind: "Field", name: { kind: "Name", value: "english" } },
                { kind: "Field", name: { kind: "Name", value: "native" } },
                { kind: "Field", name: { kind: "Name", value: "userPreferred" } },
              ],
            },
          },
          { kind: "Field", name: { kind: "Name", value: "synonyms" } },
          { kind: "Field", name: { kind: "Name", value: "siteUrl" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "coverImage" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "extraLarge" } },
                { kind: "Field", name: { kind: "Name", value: "large" } },
              ],
            },
          },
          { kind: "Field", name: { kind: "Name", value: "bannerImage" } },
          { kind: "Field", name: { kind: "Name", value: "episodes" } },
          { kind: "Field", name: { kind: "Name", value: "format" } },
          { kind: "Field", name: { kind: "Name", value: "genres" } },
          { kind: "Field", name: { kind: "Name", value: "season" } },
          { kind: "Field", name: { kind: "Name", value: "seasonYear" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "status" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "version" },
                value: { kind: "IntValue", value: "2" },
              },
            ],
          },
          { kind: "Field", name: { kind: "Name", value: "averageScore" } },
          { kind: "Field", name: { kind: "Name", value: "trending" } },
          { kind: "Field", name: { kind: "Name", value: "popularity" } },
          { kind: "Field", name: { kind: "Name", value: "favourites" } },
          { kind: "Field", name: { kind: "Name", value: "duration" } },
          { kind: "Field", name: { kind: "Name", value: "countryOfOrigin" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "source" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "version" },
                value: { kind: "IntValue", value: "3" },
              },
            ],
          },
          { kind: "Field", name: { kind: "Name", value: "isLicensed" } },
          { kind: "Field", name: { kind: "Name", value: "isAdult" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "tags" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "name" } },
                { kind: "Field", name: { kind: "Name", value: "rank" } },
                { kind: "Field", name: { kind: "Name", value: "isAdult" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "externalLinks" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "siteId" } },
                { kind: "Field", name: { kind: "Name", value: "type" } },
                { kind: "Field", name: { kind: "Name", value: "isDisabled" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "startDate" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "year" } },
                { kind: "Field", name: { kind: "Name", value: "month" } },
                { kind: "Field", name: { kind: "Name", value: "day" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "endDate" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "year" } },
                { kind: "Field", name: { kind: "Name", value: "month" } },
                { kind: "Field", name: { kind: "Name", value: "day" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "nextAiringEpisode" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "episode" } },
                { kind: "Field", name: { kind: "Name", value: "airingAt" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "studios" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "isMain" },
                value: { kind: "BooleanValue", value: true },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "nodes" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [{ kind: "Field", name: { kind: "Name", value: "name" } }],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode;
export const CatalogDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "Catalog" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "page" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "sort" } },
          type: {
            kind: "ListType",
            type: { kind: "NamedType", name: { kind: "Name", value: "MediaSort" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "search" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "genre_in" } },
          type: {
            kind: "ListType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "genre_not_in" } },
          type: {
            kind: "ListType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "tag_in" } },
          type: {
            kind: "ListType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "tag_not_in" } },
          type: {
            kind: "ListType",
            type: { kind: "NamedType", name: { kind: "Name", value: "String" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "seasonYear" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "season" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "MediaSeason" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "format" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "MediaFormat" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "status" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "MediaStatus" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "licensedById" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "countryOfOrigin" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "CountryCode" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "source" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "MediaSource" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "startDate_greater" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "FuzzyDateInt" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "startDate_lesser" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "FuzzyDateInt" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "episodes_greater" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "episodes_lesser" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "duration_greater" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "duration_lesser" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "isLicensed" } },
          type: { kind: "NamedType", name: { kind: "Name", value: "Boolean" } },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "Page" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "page" },
                value: { kind: "Variable", name: { kind: "Name", value: "page" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "perPage" },
                value: { kind: "IntValue", value: "30" },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "pageInfo" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "Field", name: { kind: "Name", value: "currentPage" } },
                      { kind: "Field", name: { kind: "Name", value: "hasNextPage" } },
                    ],
                  },
                },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "media" },
                  arguments: [
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "type" },
                      value: { kind: "EnumValue", value: "ANIME" },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "isAdult" },
                      value: { kind: "BooleanValue", value: false },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "sort" },
                      value: { kind: "Variable", name: { kind: "Name", value: "sort" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "search" },
                      value: { kind: "Variable", name: { kind: "Name", value: "search" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "genre_in" },
                      value: { kind: "Variable", name: { kind: "Name", value: "genre_in" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "genre_not_in" },
                      value: { kind: "Variable", name: { kind: "Name", value: "genre_not_in" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "tag_in" },
                      value: { kind: "Variable", name: { kind: "Name", value: "tag_in" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "tag_not_in" },
                      value: { kind: "Variable", name: { kind: "Name", value: "tag_not_in" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "seasonYear" },
                      value: { kind: "Variable", name: { kind: "Name", value: "seasonYear" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "season" },
                      value: { kind: "Variable", name: { kind: "Name", value: "season" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "format" },
                      value: { kind: "Variable", name: { kind: "Name", value: "format" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "status" },
                      value: { kind: "Variable", name: { kind: "Name", value: "status" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "licensedById" },
                      value: { kind: "Variable", name: { kind: "Name", value: "licensedById" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "countryOfOrigin" },
                      value: { kind: "Variable", name: { kind: "Name", value: "countryOfOrigin" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "source" },
                      value: { kind: "Variable", name: { kind: "Name", value: "source" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "startDate_greater" },
                      value: {
                        kind: "Variable",
                        name: { kind: "Name", value: "startDate_greater" },
                      },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "startDate_lesser" },
                      value: {
                        kind: "Variable",
                        name: { kind: "Name", value: "startDate_lesser" },
                      },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "episodes_greater" },
                      value: {
                        kind: "Variable",
                        name: { kind: "Name", value: "episodes_greater" },
                      },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "episodes_lesser" },
                      value: { kind: "Variable", name: { kind: "Name", value: "episodes_lesser" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "duration_greater" },
                      value: {
                        kind: "Variable",
                        name: { kind: "Name", value: "duration_greater" },
                      },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "duration_lesser" },
                      value: { kind: "Variable", name: { kind: "Name", value: "duration_lesser" } },
                    },
                    {
                      kind: "Argument",
                      name: { kind: "Name", value: "isLicensed" },
                      value: { kind: "Variable", name: { kind: "Name", value: "isLicensed" } },
                    },
                  ],
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      { kind: "FragmentSpread", name: { kind: "Name", value: "AniListMedia" } },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
    {
      kind: "FragmentDefinition",
      name: { kind: "Name", value: "AniListMedia" },
      typeCondition: { kind: "NamedType", name: { kind: "Name", value: "Media" } },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          { kind: "Field", name: { kind: "Name", value: "id" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "title" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "romaji" } },
                { kind: "Field", name: { kind: "Name", value: "english" } },
                { kind: "Field", name: { kind: "Name", value: "native" } },
                { kind: "Field", name: { kind: "Name", value: "userPreferred" } },
              ],
            },
          },
          { kind: "Field", name: { kind: "Name", value: "synonyms" } },
          { kind: "Field", name: { kind: "Name", value: "siteUrl" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "coverImage" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "extraLarge" } },
                { kind: "Field", name: { kind: "Name", value: "large" } },
              ],
            },
          },
          { kind: "Field", name: { kind: "Name", value: "bannerImage" } },
          { kind: "Field", name: { kind: "Name", value: "episodes" } },
          { kind: "Field", name: { kind: "Name", value: "format" } },
          { kind: "Field", name: { kind: "Name", value: "genres" } },
          { kind: "Field", name: { kind: "Name", value: "season" } },
          { kind: "Field", name: { kind: "Name", value: "seasonYear" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "status" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "version" },
                value: { kind: "IntValue", value: "2" },
              },
            ],
          },
          { kind: "Field", name: { kind: "Name", value: "averageScore" } },
          { kind: "Field", name: { kind: "Name", value: "trending" } },
          { kind: "Field", name: { kind: "Name", value: "popularity" } },
          { kind: "Field", name: { kind: "Name", value: "favourites" } },
          { kind: "Field", name: { kind: "Name", value: "duration" } },
          { kind: "Field", name: { kind: "Name", value: "countryOfOrigin" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "source" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "version" },
                value: { kind: "IntValue", value: "3" },
              },
            ],
          },
          { kind: "Field", name: { kind: "Name", value: "isLicensed" } },
          { kind: "Field", name: { kind: "Name", value: "isAdult" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "tags" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "name" } },
                { kind: "Field", name: { kind: "Name", value: "rank" } },
                { kind: "Field", name: { kind: "Name", value: "isAdult" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "externalLinks" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "siteId" } },
                { kind: "Field", name: { kind: "Name", value: "type" } },
                { kind: "Field", name: { kind: "Name", value: "isDisabled" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "startDate" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "year" } },
                { kind: "Field", name: { kind: "Name", value: "month" } },
                { kind: "Field", name: { kind: "Name", value: "day" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "endDate" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "year" } },
                { kind: "Field", name: { kind: "Name", value: "month" } },
                { kind: "Field", name: { kind: "Name", value: "day" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "nextAiringEpisode" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "episode" } },
                { kind: "Field", name: { kind: "Name", value: "airingAt" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "studios" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "isMain" },
                value: { kind: "BooleanValue", value: true },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "nodes" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [{ kind: "Field", name: { kind: "Name", value: "name" } }],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode;
export const CatalogOptionsDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "CatalogOptions" },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          { kind: "Field", name: { kind: "Name", value: "GenreCollection" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "MediaTagCollection" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "name" } },
                { kind: "Field", name: { kind: "Name", value: "category" } },
                { kind: "Field", name: { kind: "Name", value: "isAdult" } },
              ],
            },
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "ExternalLinkSourceCollection" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "type" },
                value: { kind: "EnumValue", value: "STREAMING" },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "mediaType" },
                value: { kind: "EnumValue", value: "ANIME" },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "id" } },
                { kind: "Field", name: { kind: "Name", value: "site" } },
                { kind: "Field", name: { kind: "Name", value: "type" } },
                { kind: "Field", name: { kind: "Name", value: "isDisabled" } },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode;
export const SaveProgressDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "mutation",
      name: { kind: "Name", value: "SaveProgress" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "mediaId" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
          },
        },
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "progress" } },
          type: {
            kind: "NonNullType",
            type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
          },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "SaveMediaListEntry" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "mediaId" },
                value: { kind: "Variable", name: { kind: "Name", value: "mediaId" } },
              },
              {
                kind: "Argument",
                name: { kind: "Name", value: "progress" },
                value: { kind: "Variable", name: { kind: "Name", value: "progress" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [{ kind: "Field", name: { kind: "Name", value: "progress" } }],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode;
export type Requester<C = {}> = <R, V>(
  doc: DocumentNode,
  vars?: V,
  options?: C
) => Promise<R> | AsyncIterable<R>;
export function getSdk<C>(requester: Requester<C>) {
  return {
    Viewer(variables?: ViewerQueryVariables, options?: C): Promise<ViewerQuery> {
      return requester<ViewerQuery, ViewerQueryVariables>(
        ViewerDocument,
        variables,
        options
      ) as Promise<ViewerQuery>;
    },
    User(variables: UserQueryVariables, options?: C): Promise<UserQuery> {
      return requester<UserQuery, UserQueryVariables>(
        UserDocument,
        variables,
        options
      ) as Promise<UserQuery>;
    },
    Library(variables: LibraryQueryVariables, options?: C): Promise<LibraryQuery> {
      return requester<LibraryQuery, LibraryQueryVariables>(
        LibraryDocument,
        variables,
        options
      ) as Promise<LibraryQuery>;
    },
    Catalog(variables: CatalogQueryVariables, options?: C): Promise<CatalogQuery> {
      return requester<CatalogQuery, CatalogQueryVariables>(
        CatalogDocument,
        variables,
        options
      ) as Promise<CatalogQuery>;
    },
    CatalogOptions(
      variables?: CatalogOptionsQueryVariables,
      options?: C
    ): Promise<CatalogOptionsQuery> {
      return requester<CatalogOptionsQuery, CatalogOptionsQueryVariables>(
        CatalogOptionsDocument,
        variables,
        options
      ) as Promise<CatalogOptionsQuery>;
    },
    SaveProgress(
      variables: SaveProgressMutationVariables,
      options?: C
    ): Promise<SaveProgressMutation> {
      return requester<SaveProgressMutation, SaveProgressMutationVariables>(
        SaveProgressDocument,
        variables,
        options
      ) as Promise<SaveProgressMutation>;
    },
  };
}
export type Sdk = ReturnType<typeof getSdk>;
